MODEL:
  DEVICE_ID: ('1')
  PRETRAIN_PATH: '../pretrain_model/CLIP-ViT-B-16.pt'
  NAME: 'ViT-B-16'
  ARCH_NAME: 'CLIP_baseline'
  # ARCH_NAME: 'CLIP_CVPR'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  # xhao
  TEXT_TYPE: 'captions'                       # Type of text input (options: 'captions', 'attribute')
  TEXT_FORMAT: 'hybird'
  FREEZE_TEXT: True
  USE_TEXT: False
  FREEZE_TEXT: False
  USE_TEXT: False
  TEXT_PROMPT: 2                               # Num of text prompt ("X ")
  TEXT_LEN: 120                                # context length of text for clip tokenlizer
  HEAD_UNIFORM: False                           # Whether to use a uniform contact features loss supervision

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  SAMPLER_NAME: 'RandomIdentitySampler'
  AUG: False
  NUM_INSTANCE: 8
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    TRAIN: False
    PRETRAIN_PATH: ''
  
  IMS_PER_BATCH: 128
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.000005
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  MAX_EPOCHS: 120
  CHECKPOINT_PERIOD: 121
  LOG_PERIOD: 5
  EVAL_PERIOD: 2
  
  STEPS: [30, 50]

DATASETS:
  ROOT_DIR: ('../datasets/')
  NAMES: ("CARGO")
  TESTS: ("CARGO", "CARGO_AG","CARGO_GA","CARGO_AA", "CARGO_GG", "CARGO_AGAG")

TEST:
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: 'outputs/cargo_baseline/transformer_best.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TIME_MODE: 'mix'

OUTPUT_DIR: 'outputs/cargo_baseline'

# CUDA_VISIBLE_DEVICES=4 python train_clipreid_xhao.py --config_file configs/CARGO/vit_clipreid_baseline.yml
# CUDA_VISIBLE_DEVICES=4 python test_clipreid_xhao.py --config_file configs/CARGO/vit_clipreid_baseline.yml
